### ISSUE TITLE
Not enough Memory

### ISSUE THREAD

**Issue by woodsy900** [woodsy900/DIY_PIXELSTICK_Arduino_Nano#1]
Sketch uses 27156 bytes (88%) of program storage space. Maximum is 30720 bytes.

Global variables use 2384 bytes (116%) of dynamic memory, leaving -336 bytes for local variables. Maximum is 2048 bytes.

Not enough memory; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing your footprint.

**Comment by per1234** [comment]
What are you using to compile? The code looks like it's the Arduino Web Editor, but when I compile it there I get:
```
Sketch uses 26516 bytes (86%) of program storage space. Maximum is 30720 bytes.

Global variables use 1744 bytes (85%) of dynamic memory, leaving 304 bytes for local variables. Maximum is 2048 bytes.
```
For some reason, Arduino Web Editor is using an outdated compiler version. If I compile with the Arduino IDE using Arduino AVR Boards 1.6.23 I get a bit different results, but still not over 100%:
```
Sketch uses 26192 bytes (85%) of program storage space. Maximum is 30720 bytes.
Global variables use 1867 bytes (91%) of dynamic memory, leaving 181 bytes for local variables. Maximum is 2048 bytes.
```
I know it's SRAM you're most short of, but here's an easy trick to save 70 bytes of flash and make `loop()` run slightly faster. Just add this line to your sketch:
```cpp
void serialEventRun() {}
```
The only drawback is you can no longer use the [`serialEvent()` feature](https://www.arduino.cc/reference/en/language/functions/communication/serial/serialevent/) but that's no big loss.

Other things you might try are getting rid of your use of String and using the [FastLED library](https://github.com/FastLED/FastLED) instead of Adafruit NeoPixel. I don't know what the results of that would be, but worth a try.

**Comment by per1234** [comment]
The other trick to free up flash memory is to connect an ISP programmer to your Nano, select **Tools > Board > Arduino/Genuino Uno**, do a Burn Bootloader, then use the Nano as an Uno from there on. That will free up 1.5 kB of flash due to the Uno reserving a 0.5 kB boot section for its Optiboot bootloader instead of the 2 kB boot section reserved for the bloated ATmegaBOOT bootloader used by the old Nanos (new official Nanos use optiboot but still have a 2 kB boot section).

**Comment by woodsy900** [comment]
@per1234 see that's the funny thing both you and @preecington said the same thing it comes under memory but for me it's 116% one the web editor and windows store ide as well as v1.8.7 and 1.8.6.

I use Arduino Nano set with 328P (I've tried both 328P and old bootloader option) the programmer in the IDE is set to AVR ISP. 

It isn't only at home it shows this size but even on my work computer it shows 116% Any ideas on that? Neopixel is being used purely because of the LED strip I have rgbw and fastled wasn't working with it or rather I couldn't get it to work in full.

**Comment by per1234** [comment]
>I use Arduino Nano set with 328P (I've tried both 328P and old bootloader option) the programmer in the IDE is set to AVR ISP.

Neither of those will make a difference for memory usage.

>It isn't only at home it shows this size but even on my work computer it shows 116% Any ideas on that?

When using the standard Arduino IDE, it could be a matter of which Arduino AVR Boards version you are using (check at **Tools > Board > Boards Manager**). I'm using Arduino AVR Boards 1.6.23.

It also matters which library versions you're using I'm using:

- Adafruit GFX Library 1.2.9
- Adafruit NeoPixel 1.1.6
- Adafruit SSD1306 1.1.2
- SD 1.2.2

If you turn on **File > Preferences > Show verbose output during > compilation**, the Arduino IDE will tell you which library versions are being used:
```
Using library Adafruit_NeoPixel at version 1.1.6 in folder: E:\electronics\arduino\libraries\Adafruit_NeoPixel 
Using library Adafruit_SSD1306 at version 1.1.2 in folder: E:\electronics\arduino\libraries\Adafruit_SSD1306 
Using library SPI at version 1.0 in folder: C:\ArduinoIDE\arduino-1.8.7\hardware\arduino\avr\libraries\SPI 
Using library Adafruit_GFX_Library at version 1.2.9 in folder: E:\electronics\arduino\libraries\Adafruit_GFX_Library 
Using library SD at version 1.2.2 in folder: C:\ArduinoIDE\arduino-1.8.7\libraries\SD 
Using library Wire at version 1.0 in folder: C:\ArduinoIDE\arduino-1.8.7\hardware\arduino\avr\libraries\Wire 
```
I suppose OS could also be a factor, though I haven't heard anything like that before.

I would expect the Arduino Web Editor to provide an identical environment for both of us. I would expect it would make us use the same Arduino AVR Boards versions, though the outdated compiler is suspicious. All those libraries are pre-installed so that should ensure that we are using the same library versions, but if you uploaded custom libraries it could cause that library to be used instead of the pre-installed ones. The Arduino Web Editor also shows the library versions used in the console window (sometimes hidden).

**Comment by woodsy900** [comment]
I just recompiled on the webeditor purely as you said to keep environments the same. I re-added the three libraries. I was originally using SD library number 2 (in the screenclip) but I chose number 1 this time and it presented me with 91% memory usage. 

![image](https://user-images.githubusercontent.com/24284970/46899986-e8e63100-cee6-11e8-94b7-434eb85239a6.png)

I did an upload to the Nano but nothing is showing. Probably due to high SRAM usage. But we have made progress.

**Comment by per1234** [comment]
This is the part of the Arduino Web Editor where it shows the library versions used I was talking about:
![clipboard01](https://user-images.githubusercontent.com/8572152/46900091-60698100-ce51-11e8-8de8-f0bb15bc94a6.png)
```
Multiple libraries were found for "Adafruit_NeoPixel.h"

Used: /home/ubuntu/opt/libraries/latest/adafruit_neopixel_1_1_6

Not used: /home/ubuntu/opt/libraries/latest/pinduino_1_2_10

Multiple libraries were found for "Adafruit_SSD1306.h"

Used: /home/ubuntu/opt/libraries/latest/adafruit_ssd1306_wemos_mini_oled_1_1_2

Not used: /home/ubuntu/opt/libraries/latest/adafruit_ssd1306_1_1_2

Using library adafruit_neopixel_1_1_6 at version 1.1.6 in folder: /home/ubuntu/opt/libraries/latest/adafruit_neopixel_1_1_6

Using library adafruit_ssd1306_wemos_mini_oled_1_1_2 at version 1.1.2 in folder: /home/ubuntu/opt/libraries/latest/adafruit_ssd1306_wemos_mini_oled_1_1_2

Using library SPI at version 1.0 in folder: /home/ubuntu/opt/cores/arduino/avr/libraries/SPI

Using library adafruit_gfx_library_1_2_9 at version 1.2.9 in folder: /home/ubuntu/opt/libraries/latest/adafruit_gfx_library_1_2_9

Using library sd_1_2_2 at version 1.2.2 in folder: /home/ubuntu/opt/libraries/latest/sd_1_2_2

Using library Wire at version 1.0 in folder: /home/ubuntu/opt/cores/arduino/avr/libraries/Wire
```

**Comment by woodsy900** [comment]
Yep. I checked my IDE as well and its using the same boards version as you said just FYI.
```
Multiple libraries were found for "Adafruit_NeoPixel.h"

Used: /tmp/560453380/pinned/adafruit_neopixel_1_1_6

Not used: /tmp/560453380/custom/Adafruit_NeoPixel-1.1.6

Not used: /home/ubuntu/opt/libraries/latest/pinduino_1_2_10

Not used: /home/ubuntu/opt/libraries/latest/adafruit_neopixel_1_1_6

Multiple libraries were found for "SD.h"

Used: /tmp/560453380/pinned/sd_1_2_2

Not used: /home/ubuntu/opt/libraries/latest/sd_1_2_2

Multiple libraries were found for "Adafruit_SSD1306.h"

Used: /tmp/560453380/pinned/adafruit_ssd1306_1_1_2

Not used: /tmp/560453380/custom/Adafruit_SSD1306-1.1.2

Not used: /home/ubuntu/opt/libraries/latest/adafruit_ssd1306_wemos_mini_oled_1_1_2

Not used: /home/ubuntu/opt/libraries/latest/adafruit_ssd1306_1_1_2

Using library sd_1_2_2 at version 1.2.2 in folder: /tmp/560453380/pinned/sd_1_2_2

Using library adafruit_ssd1306_1_1_2 at version 1.1.2 in folder: /tmp/560453380/pinned/adafruit_ssd1306_1_1_2

Using library SPI at version 1.0 in folder: /home/ubuntu/opt/cores/arduino/avr/libraries/SPI

Using library adafruit_gfx_library_1_2_9 at version 1.2.9 in folder: /home/ubuntu/opt/libraries/latest/adafruit_gfx_library_1_2_9

Using library adafruit_neopixel_1_1_6 at version 1.1.6 in folder: /tmp/560453380/pinned/adafruit_neopixel_1_1_6

Using library Wire at version 1.0 in folder: /home/ubuntu/opt/cores/arduino/avr/libraries/Wire

/home/ubuntu/opt/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-size -A /tmp/560453380/build/opt_PXL.ino.elf

Sketch uses 26524 bytes (86%) of program storage space. Maximum is 30720 bytes.

Global variables use 1871 bytes (91%) of dynamic memory, leaving 177 bytes for local variables. Maximum is 2048 bytes.
```

That's the output from the WEB Editor. It's very strange. Maybe the two SD libraries although identical in versions and links are bugged.


Alright sorry about the dodgey format for a moment... had to work out the insert block code... turns out you need tripple back  ticks "```" before and after

**Comment by per1234** [comment]
I notice the Arduino Web Editor chose the wrong adafruit_ssd1306 for me:
```
Using library adafruit_ssd1306_wemos_mini_oled_1_1_2 at version 1.1.2 in folder: /home/ubuntu/opt/libraries/latest/adafruit_ssd1306_wemos_mini_oled_1_1_2
```
Yours:
```
Using library adafruit_ssd1306_1_1_2 at version 1.1.2 in folder: /tmp/560453380/pinned/adafruit_ssd1306_1_1_2
```
I don't know why, since I have "starred" the correct library, and have not starred the incorrect one. I guess I would need to upload it as a "custom" library. I'm really not a fan of the Arduino Web Editor.

So I think that could be the explanation for the difference between my compile size:
```
Sketch uses 26516 bytes (86%) of program storage space. Maximum is 30720 bytes.

Global variables use 1744 bytes (85%) of dynamic memory, leaving 304 bytes for local variables. Maximum is 2048 bytes.
```
and yours:
```
Sketch uses 26524 bytes (86%) of program storage space. Maximum is 30720 bytes.

Global variables use 1871 bytes (91%) of dynamic memory, leaving 177 bytes for local variables. Maximum is 2048 bytes.`
```
Here's the "The libary to use the onboard SD slot on the Intel Edison" version of the SD library:
https://github.com/01org/corelibs-edison/tree/master/libraries/SD
I'm surprised it would even compile for Nano, since the Edison is a completely different architecture.

**Comment by woodsy900** [comment]
I think I can mark the Memory issue solved I just swapped back to the non intel edison SD library and still the same... uses 91% so I have removed that as a glitch. 

Next Issue. @per1234 would you like to become a contributor? you seem to know whats going on 👍 


Actually come to think of it... I don't know if it is solved I don't actually know what the problem was in the first place. Seems like the windows store IDE is bugged, the non-windows store version of 1.8.6 is bugged and the web editor too but then it suddenly works.

**Comment by woodsy900** [comment]
@per1234 to fix the ssd1306 library issue on the webeditor you have to upload a custom ssd1306 library its apparently a known issue where it uses the wrong one. In saying that mine is not using the custom library and is working :|

**Comment by per1234** [comment]
>would you like to become a contributor?

Sure, if you like, but I don't own the necessary hardware for the project so I'm pretty limited in what I can do. I don't mind helping out with the repository administration though. I do this already for a couple of other repositories, including the Arduino IDE repo.

>I don't actually know what the problem was in the first place.

Me neither. I expect this sort of strangeness from the Arduino Web Editor because I always have trouble with it but the Arduino IDE shouldn't have that behavior. Without being able to reproduce the issue, there's not much more that can be done to investigate.

>to fix the ssd1306 library issue on the webeditor you have to upload a custom ssd1306 library

Yeah, I know. I just didn't feel like going to the trouble since you had gotten down to the 91% global variables usage by then and I always get annoyed when I work with the Arduino Web Editor.

**Comment by per1234** [comment]
It definitely looks like a cool project. I love playing with RGB LEDs. I've only done a couple of projects with the WS2812, and they were for someone else. I keep wanting to buy some of that 144 LED/m strip but haven't been able to justify it, especially since I actually want the more expensive APA102. I did buy a couple $ worth of WS2812 just last night so I'd have some addressable LEDs to play with but I have to wait for the shipping from China.
